CEC ROR/config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'products/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

CEC ROR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

CEC ROR/app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true
	validates :category, presence: true
  	validates :description, presence: true, length: { minimum: 10 }
  	validates :quantity, presence:true
end

CEC ROR/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

CEC ROR/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :category, :description, :quantity)
    end
end

CEC ROR/app/helpers/application_helper.rb
module ApplicationHelper
end

CEC ROR/app/helpers/products_helper.rb
module ProductsHelper
end

CEC ROR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CecIT22B35</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

CEC ROR/app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %>
    <% @product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.text_area :category %>
    <% @product.errors.full_messages_for(:category).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%=form.label :quantity %><br>
    <%=form.text_area :quantity %>
    <% @product.errors.full_messages_for(:quantity).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

CEC ROR/app/views/products/edit.html.erb
<h1>Edit Products</h1>

<%= render "form", product: @product %>

CEC ROR/app/views/products/index.html.erb
<h1>Products</h1>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.name, product %>
    </li>
  <% end %>
</ul>

<%= link_to "New Product", "products/new" %>

CEC ROR/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

CEC ROR/app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p><%= @product.price %></p>
<p><%= @product.category %></p>
<p><%= @product.description %></p>
<p><%= @product.quantity %></p>

<ul>
  <li><%= link_to "Edit",  edit_product_path(@product) %></li>
  <li><%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>